### ISSUE TITLE
请问密钥对应哪些如何获取

### ISSUE THREAD

**Issue by Xo1ezw** [HdShare/PubgmhdAction#1]
appid
msdkEncodeParam
openid
sig
timestamp
roleId
userId
token

**Comment by HdShare** [comment]
手机可以通过HttpCanary/Reqable抓包

1.营地工具进入，查看url开头formal.api.gp.qq.com的POST参数
即可获取userId, token

2.福利中心进入，查看url开头c.gp.qq.com的GET参数
即可获取appid, msdkEncodeParam, openid, sig, timestamp, roleId(这里注意是uniqueRoleId参数)

**Comment by Xo1ezw** [comment]
明白了，谢谢

**Comment by HdShare** [comment]
> 明白了，谢谢

可以重新sync fork更新一下仓库，更新了点赞成功率

**Comment by Xo1ezw** [comment]
> > 明白了，谢谢
> 
> 可以重新 sync fork 更新一下仓库，更新了点赞成功率

一直在跟着更新，当天就成功运行，很不错
